STREAM_DOT_USER=stream
STREAM_DOT_HOST=r1 # (replace with your server's ip address)
STREAM_DOT_DOMAIN=$(echo $STREAM_DOT_HOST)
STREAM_DOT_SUBDOMAIN=stream
STREAM_DOT_SERVER_PORT=5723

STREAM_DOT_URL=$(echo $STREAM_DOT_SUBDOMAIN.$STREAM_DOT_DOMAIN)
STREAM_DOT_USER_HOST=$(echo $STREAM_DOT_USER@$STREAM_DOT_HOST)


STREAM_DOT_ADMIN=$USER
STREAM_DOT_ADMIN_HOST=$(echo $STREAM_DOT_ADMIN@$STREAM_DOT_HOST)
STREAM_DOT_ADMIN_PATH=$(echo /home/$STREAM_DOT_ADMIN/stream)

STREAM_DOT_REMOTE_PATH=$(echo /home/stream/live)
STREAM_DOT_REMOTE=$(echo $STREAM_DOT_USER_HOST:$STREAM_DOT_REMOTE_PATH)
